name: flutter_product_app
description: A sample Flutter product management app.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^2.0.1
  # build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg

